let shopItemsData = [
    {
      id: 1,
      name: "Casual Shirt",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/zxczxczzzcz_1600x.webp",
    },
    {
      id: 2,
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/office.webp",
    },
    {
      id: 3,
      name: "T Shirt",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/tshirt.webp",
    },
    {
      id: 4,
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-4.jpg",
    },
    {
      id: 5,
      name: "Office Shoes",
      price: 130,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/shoes.jpg",
    },
    {
      id: 6,
      name: "Niki Shoes",
      price: 70,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/niki.jpg",
    },
    {
      id: 7,
      name: "Flat Sandals",
      price: 90,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/sandal.webp",
    },
    {
      id: 8,
      name: "Casual Slipers",
      price: 90,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/slippers.jpg",
    },
    {
      id: 9,
      name: "Bags",
      price: 120,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/bags.webp",
    },
    {
      id: 10,
      name: "Lipstick Shades",
      price: 30,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/shades.jpg",
    },
    {
      id: 11,
      name: "Mockup",
      price: 150,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/mockup.jpg",
    },
    {
      id: 12,
      name: "Oil Products",
      price: 75,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/oil.jpg",
    },
  ];
  